baseURL = "https://example.org"
title = "LinkShrubbery"
languageCode = "en-us"
theme = "linkshrubbery"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Year, Your Name"
disableKinds = ["taxonomy", "term"]

# Configuration Features
[params]
  description = "Your meta description"      # Your meta description of the site
  subtitle = "Your Creative Subtitle"        # Your header subtitle
  avatar = "/images/avatar.png"          # Path to header image starting from the static directory
  logo = "/images/logo.png"
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
